// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (url)
VALUES ($1)
RETURNING id, url, created_at
`

func (q *Queries) CreateLink(ctx context.Context, url string) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, url)
	var i Link
	err := row.Scan(&i.ID, &i.Url, &i.CreatedAt)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, url, created_at FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id pgtype.UUID) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(&i.ID, &i.Url, &i.CreatedAt)
	return i, err
}
