// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (url, slug)
VALUES ($1, $2)
RETURNING id, url, slug, created_at
`

type CreateLinkParams struct {
	Url  string
	Slug pgtype.Text
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Url, arg.Slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, url, slug, created_at FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id pgtype.UUID) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, url, slug, created_at FROM links WHERE slug = $1
`

func (q *Queries) GetLinkBySlug(ctx context.Context, slug pgtype.Text) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
